theme: minima
title: fÃ¼rfriedlicheQuerdenker
author: wata-git
description: > # this means to ignore newlines until "baseurl:"
  It's my first blog in my life... 

# social links
github_username:  wata-git # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
